# f=open ("my-file.txt ")
# f=f.write()
# print(f)
# f1=f.append()
# print(f1)
# f2=f.read()
# print(f2)
# f.close

# f=open("w.txt","w")
# f.write("she is a girl")
# f.close()
# f=open("students.","r")
# a=f.read()
# print(a)
# f.close()
# f=open("students.txt","a")
# f.write("hello")
# print(f)
# f.close()

f=open("student.txt","a")
f.write("my name is honmi ")
f=open("student.txt","a")
a=f.read()
f=open("student.txt","a")
f.write("hello")
print(a)
f.close()